# Generated by Django 5.1.3 on 2024-12-13 14:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gestion_clients', '0003_alter_client_tel'),
        ('gestion_produit', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FactureVente',
            fields=[
                ('idvente', models.AutoField(primary_key=True, serialize=False)),
                ('date_facture_vente', models.DateField()),
                ('montant_facture_vente', models.DecimalField(decimal_places=2, max_digits=10)),
                ('sold_restant', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('etat_payement', models.CharField(choices=[('Payé', 'Payé'), ('Non Payé', 'Non Payé'), ('Partiellement Payé', 'Partiellement Payé')], default='Non Payé', max_length=20)),
                ('client', models.ForeignKey(db_column='id_client', on_delete=django.db.models.deletion.CASCADE, related_name='factures', to='gestion_clients.client')),
            ],
            options={
                'verbose_name': 'Facture de Vente',
                'verbose_name_plural': 'Factures de Vente',
                'db_table': 'facture_vente',
            },
        ),
        migrations.CreateModel(
            name='DetailVente',
            fields=[
                ('idDetail_vente', models.AutoField(primary_key=True, serialize=False)),
                ('quantite', models.PositiveIntegerField()),
                ('prix_unitaire', models.DecimalField(decimal_places=2, max_digits=10)),
                ('montant', models.DecimalField(decimal_places=2, max_digits=10)),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details_vente', to='gestion_produit.produit')),
                ('facture_vente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion_ventes.facturevente')),
            ],
            options={
                'db_table': 'detail_vente',
                'unique_together': {('produit', 'facture_vente')},
            },
        ),
    ]
