# Generated by Django 5.1.3 on 2024-12-14 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_clients', '0003_alter_client_tel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='date_creation',
            field=models.DateField(auto_now_add=True),
        ),
    ]
