# Generated by Django 5.1.3 on 2024-12-15 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_clients', '0004_alter_client_date_creation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='date_creation',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='i_f',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='client',
            name='numrc',
            field=models.CharField(max_length=20),
        ),
    ]
