# Generated by Django 5.1.3 on 2024-12-15 13:25

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_clients', '0006_alter_client_date_creation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='date_creation',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
