# Generated by Django 5.1.3 on 2024-12-15 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_clients', '0007_alter_client_date_creation'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='client',
            options={'ordering': ['idclient']},
        ),
    ]
