# Generated by Django 5.1.3 on 2024-12-15 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_clients', '0008_alter_client_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='adresse',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
