# Generated by Django 5.1.3 on 2024-12-15 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_clients', '0009_alter_client_adresse'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='ville',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
