# Generated by Django 5.1.3 on 2024-11-24 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fournisseur',
            fields=[
                ('idFournisseur', models.AutoField(primary_key=True, serialize=False)),
                ('Nom', models.CharField(max_length=100)),
                ('Prenom', models.CharField(max_length=100)),
                ('Tel1', models.CharField(max_length=15)),
                ('Tel2', models.CharField(blank=True, max_length=15)),
                ('Fax', models.CharField(blank=True, max_length=15)),
                ('Adresse', models.CharField(max_length=100)),
                ('Ville', models.CharField(max_length=100)),
                ('Email', models.EmailField(max_length=254)),
                ('Date_Creation', models.DateField()),
            ],
            options={
                'db_table': 'fournisseur',
                'ordering': ['Nom'],
            },
        ),
    ]
