# Generated by Django 5.1.3 on 2024-11-24 13:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_fournisseur', '0002_alter_fournisseur_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fournisseur',
            old_name='tel1',
            new_name='tel',
        ),
    ]
